owner: Arch-Network
repo: upptime
sites:
  - name: Arch Network
    url: https://arch.network
  - name: Arch RPC Gamma
    url: https://rpc-gamma.test.arch.network
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"jsonrpc":"2.0","id":"id","method":"get_block_count","params":[]}'
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: '"jsonrpc":"2.0"'
    __dangerous__body_down_if_text_missing_2: '"result":'
    __dangerous__body_down_if_text_missing_3: '"id":"id"'
status-website:
  baseUrl: /upptime
  name: Arch Network Status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "**Status**"
  introMessage: Uptime and response time for our public services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
