owner: Arch-Network
repo: upptime
sites:
  - name: Arch Network Official Web Site
    url: https://arch.network
  - name: Arch RPC Beta (https://rpc-beta.test.arch.network)
    url: https://rpc-beta.test.arch.network
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"jsonrpc":"2.0","id":"id","method":"get_block_count","params":[]}'
    __dangerous__insecure: true  
  - name: Arch RPC Gamma (https://rpc-gamma.test.arch.network)
    url: https://rpc-gamma.test.arch.network
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"jsonrpc":"2.0","id":"id","method":"get_block_count","params":[]}'
    __dangerous__insecure: true
  - name: Titan Public HTTP [Testnet] Status (https://titan-public-http.test.arch.network/status)
    url: https://titan-public-http.test.arch.network/status
    __dangerous__insecure: true
    __dangerous__body_down_if_text_missing: '"block_tip":'
    __dangerous__body_down_if_text_missing_2: '"height":'
    __dangerous__body_down_if_text_missing_3: '"runes_count":'  
  - name: Titan Public TCP [Testnet] Status (https://titan-public-tcp.test.arch.network:3030)
    check: "tcp-ping"
    url: titan-public-tcp.test.arch.network
    port: 3030
  - name: Arch Bitcoin Node (regtest)
    check: "tcp-ping"
    url: bitcoin-node.dev.aws.archnetwork.xyz
    port: 18443
  - name: Arch Bitcoin Node (testnet4)
    check: "tcp-ping"
    url: bitcoin-node.test.aws.archnetwork.xyz
    port: 49332
status-website:
  baseUrl: /upptime
  name: Arch Network Status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "**Status**"
  introMessage: Uptime and response time for our public services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
