owner: Arch-Network
repo: upptime

sites:
  - name: Arch Network
    url: https://arch.network

status-website:
  baseUrl: /upptime        
  # do NOT set cname yet
  name: Arch Network Status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "**Status**"
  introMessage: Uptime and response time for our public services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
